[tool.mypy]
exclude = 'alembic/'
strict = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 88
exclude = ".git,__pycache__,venv"
ignore = ["E203", "W503"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true

[tool.alembic]
file_template = "%%(year)d-%%(month).2d-%%(day).2d_%%(slug)s"