"""v2_create_category_in_events

Revision ID: 4c64287c3dbf
Revises: ce1d6af454b5
Create Date: 2025-06-04 14:22:40.557049

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c64287c3dbf"
down_revision: Union[str, None] = "ce1d6af454b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("category", sa.String(), nullable=False, server_default="Концерт"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "category")
    # ### end Alembic commands ###
